# Generated by Django 2.0.9 on 2021-05-19 03:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, null=True, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, null=True, verbose_name='密码')),
                ('userNumber', models.CharField(max_length=16, null=True, unique=True, verbose_name='客户端号')),
                ('fraction', models.IntegerField(default=None, validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(1)], verbose_name='分数')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rank.RankUser')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='名次')),
            ],
        ),
    ]
